package com.demo.ai.chat.data.model

/**
 * Represents the role of a message in a conversation.
 * Maps to OpenAI's ChatRole types.
 */
enum class MessageRole {
    /**
     * Message sent by the user/human.
     */
    USER,

    /**
     * Message generated by the AI assistant.
     */
    ASSISTANT,

    /**
     * System message that sets AI behavior/personality.
     * These are not persisted to database.
     */
    SYSTEM
}